# .gitlab-ci.yml
variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHA

stages:
  - build
  - test
  - deploy

# Job pour se connecter au registry GitLab
docker-login:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Job pour construire l'image Docker
build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
  dependencies:
    - docker-login

# Job pour tester le conteneur
test:
  stage: test
  script:
    - docker pull $DOCKER_IMAGE:$DOCKER_TAG
    - docker run -d -p 8090:80 --name test-container $DOCKER_IMAGE:$DOCKER_TAG
    - sleep 10
    - curl http://localhost:8090 || exit 1
    - docker stop test-container
    - docker rm test-container
  only:
    - main

# Job pour déployer
deploy:
  stage: deploy
  script:
    - docker pull $DOCKER_IMAGE:$DOCKER_TAG
    - docker stop production-container || true
    - docker rm production-container || true
    - docker run -d -p 80:80 --name production-container $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main
  when: manual